# Use this file to construct an environment
# for developing ScyJava from source.
#
#   mamba env create -f dev-environment.yml
#   conda activate scyjava-dev
#
# In addition to the dependencies needed for using ScyJava, it includes tools
# for developer-related actions like running automated tests (pytest),
# linting the code (black), and generating the API documentation (sphinx).
# If you want an environment without these tools, use environment.yml.
name: scyjava-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Project dependencies
  - jpype1
  - jgo
  # Test dependencies
  - numpy
  - pandas
  # Developer tools
  - autopep8
  - black
  - build
  - flake8
  - pytest
  - pytest-cov
  - setuptools-scm
  # Project from source
  - pip
  - pip:
    - -e .

